# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: rssfeeder
before:
  hooks:
    - make clean
    - make generate
    - make vet
    - make lint
    - make test
    - go mod download
builds:
  -
    id: "server"
    main: ./cmd/rssfeederd/main.go
    binary: rssfeederd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
  -
    id: "client"
    main: ./cmd/rssfeeder/main.go
    binary: rssfeeder
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: mradile
    name: rssfeeder
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^typo'

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - rssfeederd
    image_templates:
      - "mradile/rssfeeder:latest"
      - "mradile/rssfeeder:{{ .Major }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}.{{.Patch}}"
    skip_push: auto
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  -
    goos: linux
    goarch: arm64
    goarm: ''
    binaries:
      - rssfeederd
    image_templates:
      - "mradile/rssfeeder:latest"
      - "mradile/rssfeeder:{{ .Major }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}.{{.Patch}}"
    skip_push: auto
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  -
    goos: linux
    goarch: arm
    goarm: '6'
    binaries:
      - rssfeederd
    image_templates:
      - "mradile/rssfeeder:latest"
      - "mradile/rssfeeder:{{ .Major }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}.{{.Patch}}"
    skip_push: auto
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  -
    goos: linux
    goarch: arm
    goarm: '7'
    binaries:
      - rssfeederd
    image_templates:
      - "mradile/rssfeeder:latest"
      - "mradile/rssfeeder:{{ .Major }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}"
      - "mradile/rssfeeder:{{ .Major }}.{{ .Minor }}.{{.Patch}}"
    skip_push: auto
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"